### ISSUE TITLE
[Project] Mobile version overhaul

### ISSUE THREAD

**Issue by EeveesEyes** [hochschule-darmstadt/openartbrowser#490]
This issue collects all other issues related to mobile overhaul and should not be implemented by itself

**Reason (Why?)**
Currently there is not very much support for mobile devices. Some components are somewhat compliant to mobile standards, the rest is not. And because everybody is using their phones, we certainly should improve our mobile support.

**Solution (What?)**
Review all components for their mobile version. List all non-compliant components here:

**General**
- [x] Header (button alignment) / Footer (Wikidata logo) (#495)
- [x] Heading sizes & text overflow (#498)
- [x] Fetching List: Use full width for images (#499)
- [x] Better Tab view - select box (#500)
- [x] Carousels: Button size, slidable (#501)

**Homepage**
- [x] Hide second openArtBrowser logo

**Artwork** (#496)
- [x] update common tags component

**Movement** (#497)
- [x] Related movements timeline

**Acceptance criteria**
The mobile version is somewhat usable
